
export const ADD_TO_MY_LIST = "ADD_TO_MY_LIST";
export const REMOVE_FROM_MY_LIST = "REMOVE_FROM_MY_LIST";

export const ADD_TO_MY_WATCHED_LIST = "ADD_TO_MY_WATCHED_LIST";
export const ADD_TO_MY_WATCHED_LIST_ID = "ADD_TO_MY_WATCHED_LIST_ID";

export const REMOVE_FROM_MY_WATCHED_LIST = "REMOVE_FROM_MY_WATCHED_LIST";

export const FETCH_MOVIES_REQUEST = "FETCH_MOVIES_REQUEST";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
export const SELECT_MOIVE = "SELECT_MOIVE";
